[application]

[web.app]

# HTML title tag content
title = "neptune-gui"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[desktop]
# Set specific window dimensions and behavior
[desktop.window]
width = 400
height = 800
resizable = false # Set to true if you want to allow resizing

